name: iOS-ipa-build

on:
  workflow_dispatch:

env:
  FLUTTER_PROJECT_DIR: mobile

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}

      - run: pod repo update
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}/ios

      - run: flutter build ios --release --no-codesign
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}
        continue-on-error: true

      - name: Build unsigned IPA via xcodebuild
        run: |
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            clean build
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}/ios

      - run: mkdir Payload
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}/build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}/build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: ${{ env.FLUTTER_PROJECT_DIR }}/build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FLUTTER_PROJECT_DIR }}/build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
